controller_list:
  - name: fake_tr3_arm_controller
    joints:
      - a0
      - a1
      - a2
      - a3
      - a4
  - name: fake_tr3_gripper_controller
    joints:
      - g0
initial:  # Define initial robot poses.
  - group: tr3_arm
    pose: home