#ifndef TR_CONFIG_H
#define TR_CONFIG_H

#define CONFIG_ROSSERIAL_OVER_WIFI 1
#define CONFIG_ROSSERVER_IP "192.168.1.5"
#define CONFIG_ROSSERVER_PORT 11411
#define CONFIG_ROSSERVER_AP "TR_AN_J03NXO"
#define CONFIG_ROSSERVER_PASS "narrowroad512"

#endif