TrajectoryPlannerROS:

# Robot Configuration Parameters
  acc_lim_x: 1.0
  acc_lim_y: 0.0
  acc_lim_theta: 1.0

  max_vel_x: 1.0
  min_vel_x: 0.0

  max_vel_y: 0.0
  min_vel_y: 0.0

  max_vel_theta: 1.0
  min_vel_theta: 0.4

  min_in_place_vel_theta: 0.4
  escape_vel: -0.1
  holonomic_robot: false

# Goal Tolerance Parameters
  yaw_goal_tolerance: 6.28 #0.3
  xy_goal_tolerance: 0.40 #0.15

# Forward Simulation Parameters
  sim_time: 1.7
  sim_granularity: 0.025
  angular_sim_granularity: 0.025
  vx_samples: 0
  vy_samples: 6
  vtheta_samples: 20
  controller_frequency: 20

# Trajectory Scoring Parameters
  meter_scoring: false
  pdist_scale: 0.6
  gdist_scale: 0.8
  occdist_scale: 0.01
  heading_lookahead: 0.325
  heading_scoring: false
  heading_scoring_timestep: 0.8
  dwa: true

  oscillation_reset_dist: 0.05
  prune_plan: true

# Debugging
  publish_cost_grid_pc: false
  global_frame_id: odom
