scan_filter_chain:
- name: box_filter
  type: laser_filters/LaserScanBoxFilter
  params:
    box_frame: base_link
    max_x: 0.390
    max_y: 0.200
    max_z: 0.300
    min_x: -0.390
    min_y: -0.600
    min_z: -0.300
    invert: false
