scan_filter_chain:
- name: box_filter
  type: laser_filters/LaserScanBoxFilter
  params:
    box_frame: base_link
    max_x: 0.200
    max_y: 25.000
    max_z: 0.300
    min_x: -25.000
    min_y: -25.000
    min_z: -0.300
    invert: false
