tr3:
  joints:
    a0:
      pid: [9.0, 5.0, 0.2]
    a1:
      pid: [9.0, 5.0, 0.2]
    a2:
      pid: [9.0, 5.0, 0.2]
    a3:
      pid: [9.0, 5.0, 0.2]
    a4:
      pid: [9.0, 5.0, 0.2]
    g0:
      pid: [9.0, 5.0, 0.2]
    h0:
      pid: [9.0, 5.0, 0.2]
    h1:
      pid: [9.0, 5.0, 0.2]
    b0:
      pid: [9.0, 5.0, 0.2]
    b1:
      pid: [9.0, 5.0, 0.2]
